// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AddHobbyBlock': string;
  'Button': string;
  'ButtonAddHobby': string;
  'InputHobbyName': string;
  'InputHobbyPassion': string;
  'InputHobbyYear': string;
  'TextInput': string;
}
declare var cssExports: CssExports;
export = cssExports;
