// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AddUserBlock': string;
  'Button': string;
  'ButtonAddUser': string;
  'InputUserName': string;
  'TextInput': string;
}
declare var cssExports: CssExports;
export = cssExports;
